# Déclenché à chaque push
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Branche de destination
          PAGES_BRANCH: gh-pages
          # Token d'accès personnel
          TOKEN: ${{ secrets.TOKEN }}
          # Ou pour publier sur le même repo, utilisez le token automatique
          # TOKEN: ${{ secrets.GITHUB_TOKEN }}
